### ISSUE TITLE
Keep getting error when trying to run galley template 

### ISSUE THREAD

**Issue by kodeninja** [twitter-fabric/galley#41]
```
$ npm install -g galley-cli
$ git clone https://github.com/twitter-fabric/galley-template.git
$ cd galley-template
$ galley run demo.dev

...npm i...

demo-mysql: Downloading… ⠇ Pulling from library/mysql                                                     
undefined:2
{"status":"Pulling fs layer","progressDetail":{},"id":"9374bfd4d273"}
^
SyntaxError: Unexpected token {
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/private/tmp/galley-demo/galley-template/node_modules/galley/build/lib/lib/docker_utils.js:239:21)
    at IncomingMessage.emit (events.js:95:17)
    at IncomingMessage.<anonymous> (_stream_readable.js:765:14)
    at IncomingMessage.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at IncomingMessage.Readable.push (_stream_readable.js:128:10)
    at HTTPParser.parserOnBody [as onBody] (http.js:143:22)
    at Socket.socketOnData [as ondata] (http.js:1588:20)
    at Pipe.onread (net.js:528:27)
```

**Versions**:
`OS X Yosemite 10.10.5`

```
$ node -v && npm -v && galley version
v0.10.36
1.4.2
galley version 1.0.0
```
Not sure why it keeps barfing while trying to download the `mysql` docker image.

**Comment by samn** [comment]
Hey @kodeninja, thanks for trying Galley! 
I'm not 100% sure but I suspect that the version of node you're using (0.10.36, which is pretty old) is the culprit here. Can you try upgrading node to a newer version?

**Comment by kodeninja** [comment]
Thanks for replying, @samn!

I switched to `node 4`, and that threw the same error. But, upgrading to `node 6` worked (I didn't try `node 5`)!

I think specifying the _minimum_ `node` version in Galley's `package.json` would be helpful: https://docs.npmjs.com/files/package.json#engines

**Comment by samn** [comment]
Great idea @kodeninja, thanks for the suggestion.
I'll make sure this is better documented going forward :)

**Comment by finneganh** [comment]
Hrm. Looks like something around getting the string out of the buffer for
pulls. This code changed recently, perhaps in a poorly-compatible way.

**Comment by finneganh** [comment]
Also that's an older version of Galley. It's at 1.0.3 now, which may still have had an issue w/ above but it might have been better.
